config/routes.rb
Ogyam::Application.routes.draw do
  
  resources :users
  resources :password_resets
  resources :sessions, only: [:new, :create, :destroy]
  resources :goals, only:[:create, :destroy]

  match  '/signup', to: 'users#new'
  match  '/signin', to:  'sessions#new'
  match  '/signout',  to:  'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/terms', to: 'static_pages#terms'
  match '/blog',  to: 'static_pages#blog'
  match '/press', to: 'static_pages#press'
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  default_scope order: 'goals.created_at DESC'
end

app/models/motivation.rb
class Motivation < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :bio, :email, :image_url, :location, :name,
    :password, :password_confirmation
  
  has_many :goals, dependent: :destroy
  has_many :motivations

  has_secure_password

  before_save :downcase_email 
  before_save :add_gravatar
  before_save :create_remember_token

  VALID_REGEX = /\A[\w+@\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: VALID_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_digest, presence: true

  def send_password_reset
    self.password_reset_token = SecureRandom.urlsafe_base64
    self.password_reset_sent_at = Time.zone.now
    self.save!(validate: false)
    UserMailer.password_reset(self).deliver  
  end
  
  def feed
    Goal.where("user_id = ?", self.id)
  end

  private
    def downcase_email
      self.email.downcase 
    end

    def gravatar_for(user)
      default_url = "https://still-shore-2532.herokuapp.com/assets/avatar.png"
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=44&d=#{CGI.escape(default_url)}" 
    end

    def add_gravatar
      self.image_url = gravatar_for(self) 
    end

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy

  def create
    @goal = current_user.goals.build(params[:goal])
    if @goal.save
      flash[:success] = "Goal created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @goal.destroy
    redirect_to root_path
  end
  
  private

    def correct_user
      @goal = current_user.goals.find_by_id(params[:id])
      redirect_to root_path if @goal.nil? 
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_path, :notice => "Email has been sent with password reset"
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params[:user])
      sign_in @user
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @goal = current_user.goals.build
      @feed_items = current_user.feed
    end
  end

  def help
  end

  def about
  end

  def blog
  end

  def terms
  end

  def press
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def index
  end

  def show
    @user = User.find(params[:id]) 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user 
      flash[:success] = "Welcome to Ogyam"
      redirect_to @user
      UserMailer.registration_confirmation(@user).deliver
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile has been succesfully updated!"
      redirect_to @user
    else
      render 'edit' 
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "user destroyed"
    redirect_to users_path
  end

  private
    def correct_user
      @user = User.find(params[:id]) 
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

   # Returns the full title on a per-page basis.
    def full_title(page_title)
      base_title = "Ogyam"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token     
    self.current_user = user
  end

  def signed_in?
    !current_user.nil? 
  end

  def current_user=(user)
    @current_user = user 
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token) 
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      flash[:notice] = "Please sign in"
      redirect_to signin_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/goals/_goal.html.erb
<li>
 <span class="content"><%= goal.content %></span>
 <span class="timestamp">
   Posted <%= time_ago_in_words(goal.created_at) %>
 </span>
 <% if current_user?(goal.user)  %>
   <%= link_to "delete", goal, method: :delete,
                               confirm: "You sure"
                               title: goal.content %>
 <% end %>
</li>

app/views/layouts/_footer.html.erb
<% if signed_in? %>
<% else %>
  <footer id="footer" class="footer">
  <div class="container">
    <div class="row-fluid">
      <div class="span4">
        <a class="pull-left footer-logo" href="<%= root_path %>"></a>
      </div>

      <div class="span5">
        <ul class="unstyled inline social-icons">
          <li><a href="#"><i class="icon-facebook"></i></a></li>
          <li><a href="#"><i class="icon-twitter"></i></a></li>
          <li><a href="#"><i class="icon-pinterest"></i></a></li>
          <li><a href="#"><i class="icon-linkedin-sign"></i></a></li>
          <li><a href="#"><i class="icon-google-plus"></i></a></li>
        </ul>
      </div>
      <div class="span3">
        <ul class="unstyled site-map">
          <li> <%= link_to "About", about_path%> </li>
          <li> <%= link_to "Blog", blog_path%> </li>
          <li> <%= link_to "Terms", terms_path %> </li>
          <li> <%= link_to "Help", help_path %> </li>
          <li> <%= link_to "Press Kit", '#'%> </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="contact-form-wrapper">
          <span class="contact-btn closed">Contact Form</span>
          <div class="contact-form-inner">
            <form class="contact-form">
              <fieldset>
                <input class="input-block-level" type="text" name="name" placeholder="your name">
                <input class="input-block-level" type="email" name="email" placeholder="your email">
                <textarea class="input-block-level" rows="3" name="message" placeholder="your message"></textarea>
                <button class="btn btn-success" type="submit">Submit</button>
              </fieldset>
            </form>
          </div>
        </div>
  </footer>
<% end %>

app/views/layouts/_header.html.erb
<header id="header" class="header page">
<div class="navbar-fixed-top navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Ogyam", root_path, class: "brand" %>
      <ul class="nav  pull-right">
        <% if signed_in? %>
          <li> <%= link_to "Profile", current_user %> </li>
          <li> <%= link_to "Settings", edit_user_path(current_user) %> </li>
          <li> <%= link_to "Logout", '/signout', method: "delete" %> </li>
        <% else %>
          <li> <%= link_to "Login", signin_path %> </li>
          <li> <%= link_to "Signup", signup_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if IE 7]>
  <link rel="stylesheet" href="css/font-awesome-ie7.min.css">
  <link rel="stylesheet" href="css/font-awesome-more-ie7.min.css">
<![endif]-->

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))  %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
  <%= javascript_include_tag "application" %>
</html>

app/views/layouts/loginlayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))  %></title>
  <%= stylesheet_link_tag    "boot", :media => "all" %>
  <%= stylesheet_link_tag    "registrationpages", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/password_resets/edit.html.erb
</header>
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <div class="field">
    <%= f.password_field(:password, placeholder: "password", class: "login password-field")  %>
  </div>

  <div class="field">
    <%= f.password_field(:password_confirmation, placeholder: "retype password", class: "login password-field")  %>
  </div>

  <div>
    <%= f.submit("Reset password", class: "", class: "button btn btn-large") %>   
  </div>
<% end %>

app/views/password_resets/new.html.erb
</header>
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains  <%= pluralize(object.errors.count, "error")  %>
    <ul>
      <% object.errors.full_messages.each do |msg|  %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="goals">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>"></li>
<%= link_to image_tag(feed_item.user.image_url), feed_item.user %>
<%= link_to feed_item.user.name, feed_item.user %>
<p>
<%= feed_item.content %>
</p>
 <% if current_user?(feed_item.user)  %>
   <%= link_to "delete", feed_item, method: :delete,
                               confirm: "You sure",
                               title: feed_item.content %>
 <% end %>
<p>
  Posted <%= time_ago_in_words(feed_item.created_at)  %> ago.
</p>

app/views/shared/_goal_form.html.erb
<%= form_for(@goal) do |f| %>
  <div class="field">
  <%= render 'shared/error_messages', object: @goal %>
    <%= f.text_area :content, placeholder: "New goal" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
</header>
<a href="<%= user_path(current_user) %>">
  <%= image_tag(current_user.image_url, alt: current_user.name) %>
</a>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.goals.count,"goal")%></span>
<span><%= pluralize(current_user.goals.count,"post")%></span>
<span><%= pluralize(current_user.goals.count,"motivation")%> </span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="container">
  <div class="row-fluid">
    <div class="span12">
      <div class="header-description pull-left">
        <h1>About Oyam! </h1>
      </div><!-- /header-description -->

    </div><!-- /span12 -->
  </div><!-- /row-fluid -->
</div><!-- /container -->
</header>

<div class="page-content">

  <div class="container">
    <div class="row-fluid">
        <!--</div>[> /span4 <]-->
      <div class="span2">
      </div> 
      <div class="span8">

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer enim diam, rutrum et vehicula a, ornare ullamcorper neque. Etiam vitae mollis nulla. Sed vestibulum, lacus eget iaculis pharetra, arcu ipsum fermentum risus, condimentum mattis diam leo et leo. Integer quis neque eget urna tempus congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla semper pellentesque magna, non elementum orci sodales a. Sed quis sapien diam, euismod egestas risus. Cras non lorem in metus tempor tempor vitae id neque. Duis id eros ultrices diam placerat ullamcorper. Etiam quis nulla ante, eget vehicula tellus. Suspendisse potenti. Vestibulum dui odio, elementum sit amet tincidunt sed, dapibus eu tortor. Cras a lorem urna.

        Pellentesque at urna malesuada lorem tristique interdum. Fusce tincidunt est feugiat ligula luctus ornare. Sed in urna velit, auctor dictum tellus. Aenean commodo magna non magna dictum venenatis. Curabitur ut leo non sapien interdum convallis. Etiam diam arcu, placerat quis interdum a, aliquet sit amet neque. Duis id enim sit amet odio consectetur convallis ac ut lacus. Donec dui nisi, ultrices non tincidunt et, auctor a orci. Integer vitae sem eget tortor pharetra pharetra. Curabitur egestas laoreet lacus, eu pellentesque lorem consequat a. Morbi nec convallis nulla. In dictum, turpis non aliquet congue, mi nunc varius justo, quis egestas lorem nisi ac ipsum. Morbi fringilla nunc eget odio porta adipiscing. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque sapien tellus, porttitor aliquam iaculis ac, mollis ut magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
        </p>
        Pellentesque a mi nec arcu varius vulputate. Donec ac convallis lectus. Mauris at massa ut nunc mattis semper ac id quam. Nunc in lorem nibh, quis feugiat nibh. Proin convallis, purus vel luctus luctus, odio est eleifend magna, sit amet laoreet enim nibh vel justo. Sed enim lorem, viverra eu aliquam ornare, fringilla rhoncus ante. Sed nisl nisl, convallis lobortis semper at, sodales et turpis. Nam urna erat, interdum et pulvinar in, elementum in metus.

        <p>
        Etiam sit amet ligula at lacus iaculis ultricies. Nam ut nunc ac lacus venenatis consequat. Maecenas at turpis sit amet elit ultrices placerat. Curabitur a nisl et tortor blandit rhoncus. Vestibulum consectetur augue quis turpis fermentum rutrum. Vestibulum ultricies tempus erat. Curabitur sollicitudin suscipit facilisis. Morbi vestibulum convallis iaculis. Duis et sem non velit sodales posuere.
        </p>
        <p>
        Nullam elementum velit ut orci sagittis feugiat. Integer lacus ligula, varius quis ornare quis, imperdiet quis tellus. Ut faucibus neque ut neque fermentum placerat. Aenean libero purus, tincidunt ac varius ut, porta in erat. Aenean id nunc pretium enim ultricies interdum. Curabitur imperdiet lacus ut diam hendrerit quis consectetur quam ultricies. Fusce aliquam porttitor molestie. Fusce faucibus mauris a diam aliquam sed sodales nisl feugiat.</p>
      </div><!-- /span6 -->
    </div><!-- /row-fluid -->
  </div><!-- /container -->

  <div class="span2">
  </div> 
</div><!-- /page-content -->

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<div class="container">
  <div class="row-fluid">
    <div class="span12">
      <div class="header-description pull-left">
        <h1>SmartMap: Blog </h1>
      </div><!-- /header-description -->

    </div><!-- /span12 -->
  </div><!-- /row-fluid -->
</div><!-- /container -->
</header>

<div class="page-content">

  <div class="container">
    <div class="row-fluid">
      <div class="span6">
        <article class="blog-post">
        <h4 class="entry-title"><a href="#">Proin sit amet scelerisque erat</a></h4>
        <img src="/assets/screenshot.jpg" alt="blog image" />

        <div class="meta-tags">
          <a class="link" href="#">10 days ago</a>
          <a class="link" href="#">Video, Photo</a>
          <a class="link" href="#">10 comments</a>
        </div>

        <p>In malesuada posuere ullamcorper. Donec et mi nulla, dapibus venenatis ligula. Nam porta tristique blandit. In a libero in quam vestibulum dictum. Suspendisse dui velit, vehicula at interdum eget, rutrum sed ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent sit amet neque eu orci euismod interdum. Duis ac lacus vitae dolor pulvinar ultricies a et elit. Nam sit amet ligula et leo pellentesque vulputate at eu magna. Cras nisl magna, iaculis nec bibendum eget, volutpat eget nisl. Nam congue rhoncus tellus in blandit.</p>

        <a class="btn btn-danger" href="single.html">Read more...</a>
        </article>                  
      </div><!-- /span6 -->

      <div class="span6">
        <article class="blog-post">
        <h4 class="entry-title"><a href="#">Proin sit amet scelerisque erat</a></h4>
        <img src="/assets/screenshot.jpg" alt="blog image" />

        <div class="meta-tags">
          <a class="link" href="#">10 days ago</a>
          <a class="link" href="#">Video, Photo</a>
          <a class="link" href="#">10 comments</a>
        </div>

        <p>In malesuada posuere ullamcorper. Donec et mi nulla, dapibus venenatis ligula. Nam porta tristique blandit. In a libero in quam vestibulum dictum. Suspendisse dui velit, vehicula at interdum eget, rutrum sed ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent sit amet neque eu orci euismod interdum. Duis ac lacus vitae dolor pulvinar ultricies a et elit. Nam sit amet ligula et leo pellentesque vulputate at eu magna. Cras nisl magna, iaculis nec bibendum eget, volutpat eget nisl. Nam congue rhoncus tellus in blandit.</p>

        <a class="btn btn-danger" href="single.html">Read more...</a>
        </article>                  
      </div><!-- /span6 -->

      <div class="span6">
        <article class="blog-post">
        <h4 class="entry-title"><a href="#">Proin sit amet scelerisque erat</a></h4>
        <img src="/assets/screenshot.jpg" alt="blog image" />

        <div class="meta-tags">
          <a class="link" href="#">10 days ago</a>
          <a class="link" href="#">Video, Photo</a>
          <a class="link" href="#">10 comments</a>
        </div>

        <p>In malesuada posuere ullamcorper. Donec et mi nulla, dapibus venenatis ligula. Nam porta tristique blandit. In a libero in quam vestibulum dictum. Suspendisse dui velit, vehicula at interdum eget, rutrum sed ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent sit amet neque eu orci euismod interdum. Duis ac lacus vitae dolor pulvinar ultricies a et elit. Nam sit amet ligula et leo pellentesque vulputate at eu magna. Cras nisl magna, iaculis nec bibendum eget, volutpat eget nisl. Nam congue rhoncus tellus in blandit.</p>

        <a class="btn btn-danger" href="single.html">Read more...</a>
        </article>                  
      </div><!-- /span6 -->

      <div class="span6">
        <article class="blog-post">
        <h4 class="entry-title"><a href="#">Proin sit amet scelerisque erat</a></h4>
        <img src="/assets/screenshot.jpg" alt="blog image" />

        <div class="meta-tags">
          <a class="link" href="#">10 days ago</a>
          <a class="link" href="#">Video, Photo</a>
          <a class="link" href="#">10 comments</a>
        </div>

        <p>In malesuada posuere ullamcorper. Donec et mi nulla, dapibus venenatis ligula. Nam porta tristique blandit. In a libero in quam vestibulum dictum. Suspendisse dui velit, vehicula at interdum eget, rutrum sed ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent sit amet neque eu orci euismod interdum. Duis ac lacus vitae dolor pulvinar ultricies a et elit. Nam sit amet ligula et leo pellentesque vulputate at eu magna. Cras nisl magna, iaculis nec bibendum eget, volutpat eget nisl. Nam congue rhoncus tellus in blandit.</p>

        <a class="btn btn-danger" href="single.html">Read more...</a>
        </article>                  
      </div><!-- /span6 -->
    </div><!-- /row-fluid -->
  </div><!-- /container -->

</div><!-- /page-content -->

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="container">
  <div class="row-fluid">
    <div class="span12">
      <div class="header-description pull-left">
        <h1>About Oyam! </h1>
      </div><!-- /header-description -->

    </div><!-- /span12 -->
  </div><!-- /row-fluid -->
</div><!-- /container -->
</header>

<div class="page-content">

  <div class="container">
    <div class="row-fluid">
        <!--</div>[> /span4 <]-->
      <div class="span2">
      </div> 
      <div class="span8">

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer enim diam, rutrum et vehicula a, ornare ullamcorper neque. Etiam vitae mollis nulla. Sed vestibulum, lacus eget iaculis pharetra, arcu ipsum fermentum risus, condimentum mattis diam leo et leo. Integer quis neque eget urna tempus congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla semper pellentesque magna, non elementum orci sodales a. Sed quis sapien diam, euismod egestas risus. Cras non lorem in metus tempor tempor vitae id neque. Duis id eros ultrices diam placerat ullamcorper. Etiam quis nulla ante, eget vehicula tellus. Suspendisse potenti. Vestibulum dui odio, elementum sit amet tincidunt sed, dapibus eu tortor. Cras a lorem urna.

        Pellentesque at urna malesuada lorem tristique interdum. Fusce tincidunt est feugiat ligula luctus ornare. Sed in urna velit, auctor dictum tellus. Aenean commodo magna non magna dictum venenatis. Curabitur ut leo non sapien interdum convallis. Etiam diam arcu, placerat quis interdum a, aliquet sit amet neque. Duis id enim sit amet odio consectetur convallis ac ut lacus. Donec dui nisi, ultrices non tincidunt et, auctor a orci. Integer vitae sem eget tortor pharetra pharetra. Curabitur egestas laoreet lacus, eu pellentesque lorem consequat a. Morbi nec convallis nulla. In dictum, turpis non aliquet congue, mi nunc varius justo, quis egestas lorem nisi ac ipsum. Morbi fringilla nunc eget odio porta adipiscing. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque sapien tellus, porttitor aliquam iaculis ac, mollis ut magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
        </p>
        Pellentesque a mi nec arcu varius vulputate. Donec ac convallis lectus. Mauris at massa ut nunc mattis semper ac id quam. Nunc in lorem nibh, quis feugiat nibh. Proin convallis, purus vel luctus luctus, odio est eleifend magna, sit amet laoreet enim nibh vel justo. Sed enim lorem, viverra eu aliquam ornare, fringilla rhoncus ante. Sed nisl nisl, convallis lobortis semper at, sodales et turpis. Nam urna erat, interdum et pulvinar in, elementum in metus.

        <p>
        Etiam sit amet ligula at lacus iaculis ultricies. Nam ut nunc ac lacus venenatis consequat. Maecenas at turpis sit amet elit ultrices placerat. Curabitur a nisl et tortor blandit rhoncus. Vestibulum consectetur augue quis turpis fermentum rutrum. Vestibulum ultricies tempus erat. Curabitur sollicitudin suscipit facilisis. Morbi vestibulum convallis iaculis. Duis et sem non velit sodales posuere.
        </p>
        <p>
        Nullam elementum velit ut orci sagittis feugiat. Integer lacus ligula, varius quis ornare quis, imperdiet quis tellus. Ut faucibus neque ut neque fermentum placerat. Aenean libero purus, tincidunt ac varius ut, porta in erat. Aenean id nunc pretium enim ultricies interdum. Curabitur imperdiet lacus ut diam hendrerit quis consectetur quam ultricies. Fusce aliquam porttitor molestie. Fusce faucibus mauris a diam aliquam sed sodales nisl feugiat.</p>
      </div><!-- /span6 -->
    </div><!-- /row-fluid -->
  </div><!-- /container -->

  <div class="span2">
  </div> 
</div><!-- /page-content -->

app/views/static_pages/press.html.erb
<% provide(:title, 'Press') %>
<h1>StaticPages#press</h1>
<p>Find me in app/views/static_pages/press.html.erb</p>

app/views/users/_user.html.erb
<li>
  <%= image_tag(user.image_url) %>
  <%= link_to user.name, user %>
  <% if current_user.admin?  && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, confirm: "Sure?" %>
  <% end %>
</li>

app/views/users/index.html.erb
</header>
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<ul class="users">
   <% User.all.each do |user| %>
     <%= render user %>
   <% end %>
</ul>